# Config file for Telegram Captcha Bot

# Button text
button_text = "点这里"

# Bot sends this message to new users
welcome_message = "欢迎加入，请在5分钟内点击下方按钮，之后即可正常发言。"

# Edit welcome message with this text if user passed validation
after_success_message = "验证通过"

# Edit welcome message with this text if user failed validation
after_fail_message = "User didn't pass the validation and was banned."

# Show success and failure messages or delete them. Pick "show" or "del"
print_success_and_fail_messages_strategy = "del"

# During this time in seconds, the new user have to press the captha button
welcome_timeout = "300"

# If the new user does not press the button, the bot will ban the user for this duration of time. Can be "forever" or number of minutes ("10")
ban_duration = "2"

# Do you want to use a socks5 proxy server? Can be "yes" or "no"
use_socks5_proxy = "no"

# Socks5 proxy server IP address
socks5_address = "1.1.1.1"

# Socks5 proxy server TCP port
socks5_port = "1080"

# Socks5 proxy server username
socks5_login = "login"

# Socks5 proxy server password
socks5_password = "password"
