name: goreleaser

on:
  pull_request:
  push:

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
